In this pipeline we are happy with Prodigal failing

diff --git a/modules/nf-core/busco/busco/busco-busco.diff b/modules/nf-core/busco/busco/busco-busco.diff
--- a/modules/nf-core/busco/busco/busco-busco.diff
+++ b/modules/nf-core/busco/busco/busco-busco.diff
@@ -1,5 +1,4 @@
 Changes in component 'nf-core/busco/busco'
-'modules/nf-core/busco/busco/environment.yml' is unchanged
 'modules/nf-core/busco/busco/meta.yml' is unchanged
 Changes in 'busco/busco/main.nf':
 --- modules/nf-core/busco/busco/main.nf
@@ -21,8 +20,25 @@ Changes in 'busco/busco/main.nf':
      def intermediate_files = [
          './*-busco/*/auto_lineage',
          './*-busco/*/**/{miniprot,hmmer,.bbtools}_output',
+@@ -112,8 +111,13 @@
+ 
+     if grep 'Run failed; check logs' ${prefix}-busco.batch_summary.txt > /dev/null
+     then
+-        echo "Busco run failed"
+-        exit 1
++        if grep -Fx 'Sequence too long (max 32000000 permitted).' ${prefix}-busco.log > /dev/null
++        then
++            echo "Prodigal can't run on this genome. Skipping it"
++        else
++            echo "Busco run failed"
++            exit 1
++        fi
+     fi
+ 
+     cat <<-END_VERSIONS > versions.yml
 
-'modules/nf-core/busco/busco/tests/main.nf.test.snap' is unchanged
-'modules/nf-core/busco/busco/tests/nextflow.config' is unchanged
+'modules/nf-core/busco/busco/environment.yml' is unchanged
 'modules/nf-core/busco/busco/tests/main.nf.test' is unchanged
+'modules/nf-core/busco/busco/tests/nextflow.config' is unchanged
+'modules/nf-core/busco/busco/tests/main.nf.test.snap' is unchanged
 ************************************************************
